### ISSUE TITLE
Splide type loop for product carousel

### ISSUE THREAD

**Issue by Bartdegroot** [blackbird-agency/hyva-splide-js#1]
Is it possible to use the type option loop for the Splide slider with products. This causes Splide to generate clones, but creates an alpine error when the swatches are visible:

![image](https://github.com/blackbird-agency/hyva-splide-js/assets/26902040/b1dfacad-d91f-4284-9b37-ed6706d0c576)

For now, we can use the rewind option, but it would be awesome to use the loop option.

**Comment by luderic-blackbird** [comment]
Hello, 

Which Hyvä Themes version are you using ?

**Comment by Bartdegroot** [comment]
We are using the latest version (1.3.1).

**Comment by luderic-blackbird** [comment]
Hello @Bartdegroot,

I just tried to install a blank Magento, I installed Hyva Thème version 1.3.1 and the hyva-splide-js module.

I haven't noticed any problems using the `loop` type to create a product card carousel.

The problem you have reported is not a problem with the module, but probably a problem in its implementation.

Below you'll find a gif showing that the `loop` type works well even with product cards.

Make sure you don't mix the default slider proposed by Hyvä with the SplideJS module's slider. It's best to remove all the code from the default slider.
That's what I've done and I haven't noticed any problems.

Perhaps I've misunderstood the problem, but if so, please don't hesitate to give me more details.

![issue-1](https://github.com/blackbird-agency/hyva-splide-js/assets/144663333/4473bd87-2039-4447-baab-8c5ab8fe4966)

**Comment by luderic-blackbird** [comment]
Hello,

I've been able to start testing on my own, and I've noticed the bug.

I'll look into it as soon as I have some free time.

The module only loads the SplideJS library and makes it available to the whole project.
However, the problem come from the poor compatibility between the library SplideJS and Hyvä.

I don't think that a patch to the module will be able to correct this, as it will be necessary to modify the way swatches work in Hyvä to fix this problem.

**Comment by luderic-blackbird** [comment]
The problem come from the poor compatibility between the library SplideJS `loop` type and Hyvä, as it would be necessary to modify the way swatches work in Hyvä to fix this problem.

I will not modify the way Hyvä core works inside this module.
